# GFALL

Import the `GFALLReader` class.

In [1]:
from carsus.io.kurucz import GFALLReader

 ChiantiPy version 0.8.4
 found PyQt5 widgets
 using PyQt5 widgets

By default, `gfall.dat` is read directly from Harvard's server.

In [2]:
gfall_reader = GFALLReader()

[    carsus.io.kurucz.gfall][WARNING] - A specific combination to identify unique levels from GFALL data has not been given. Defaulting to ["energy", "j"]. (gfall.py:86)

In [3]:
gfall_reader.gfall

[    carsus.io.kurucz.gfall][INFO] - Parsing GFALL: http://kurucz.harvard.edu/linelists/gfall/gfall.dat (gfall.py:139)

,wavelength,loggf,blank1,blank2,log_gamma_rad,log_gamma_stark,log_gamma_vderwaals,ref,isotope,log_f_hyperfine,...,hyperfine_f_lower,hyperfine_f_upper,hyperfine_note_lower,hyperfine_note_upper,lande_g_lower,lande_g_upper,energy_lower_predicted,energy_upper_predicted,atomic_number,ion_charge
0,2.4898,-0.842,NaN,NaN,11.73,0.00,0.00,NBS,0.0,0.0,...,NaN,NaN,NaN,NaN,0.0,0.0,False,False,7,5
1,2.8787,-0.171,NaN,NaN,12.26,0.00,0.00,NBS,0.0,0.0,...,NaN,NaN,NaN,NaN,0.0,0.0,False,False,7,5
2,5.2682,-0.870,NaN,NaN,0.00,0.00,0.00,NBS,0.0,0.0,...,NaN,NaN,NaN,NaN,0.0,0.0,False,False,5,3
3,6.0313,-0.215,NaN,NaN,0.00,0.00,0.00,NBS,0.0,0.0,...,NaN,NaN,NaN,NaN,0.0,0.0,False,False,5,3
4,6.1092,-5.150,NaN,NaN,0.00,0.00,0.00,DRA,0.0,0.0,...,NaN,NaN,NaN,NaN,0.0,0.0,False,False,5,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564920,99694.5982,-1.886,NaN,NaN,8.23,-5.18,-7.48,K94,0.0,0.0,...,NaN,NaN,NaN,NaN,1491.0,1355.0,False,False,26,0
564921,99713.4910,-4.028,NaN,NaN,8.73,-5.55,-7.52,K88,0.0,0.0,...,NaN,NaN,NaN,NaN,1302.0,814.0,False,False,26,1
564922,99753.2890,0.529,NaN,NaN,6.97,-2.60,-6.58,K88,0.0,0.0,...,NaN,NaN,NaN,NaN,1000.0,0.0,False,False,20,0
564924,99768.2213,-3.114,NaN,NaN,8.33,-4.99,-7.49,K,0.0,0.0,...,NaN,NaN,NaN,NaN,1.0,489.0,False,False,22,0
564925,99962.7500,-2.878,NaN,NaN,7.67,-1.54,-6.46,K88,0.0,0.0,...,NaN,NaN,NaN,NaN,1501.0,1000.0,False,False,20,0

A raw version of the file is stored inside the `gfall_raw` attribute.

In [4]:
gfall_reader.gfall_raw

,wavelength,loggf,element_code,e_first,j_first,blank1,label_first,e_second,j_second,blank2,...,hyperfine_f_first,hyperfine_note_first,blank4,hyperfine_f_second,hyperfine_note_second,line_strength_class,line_code,lande_g_first,lande_g_second,isotopic_shift
0,2.4898,-0.842,7.05,0.000,0.0,NaN,1s2 1S,4016390.000,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN
1,2.8787,-0.171,7.05,0.000,0.0,NaN,1s2 1S,3473790.000,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN
2,5.2682,-0.870,5.03,0.000,0.0,NaN,1s2 1S,1898180.000,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN
3,6.0313,-0.215,5.03,0.000,0.0,NaN,1s2 1S,1658020.000,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN
4,6.1092,-5.150,5.03,0.000,0.0,NaN,1s2 1S,1636882.000,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564981,452493.3210,3.578,1.00,109430.063,5.5,NaN,AVERAGE,109452.156,6.5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN
564982,518497.2090,3.637,1.00,109452.156,6.5,NaN,AVERAGE,109471.438,7.5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN
564983,591062.8690,3.694,1.00,109471.438,7.5,NaN,AVERAGE,109488.352,8.5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN
564984,669623.8150,3.748,1.00,109488.352,8.5,NaN,AVERAGE,109503.281,9.5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN
564985,754956.4080,3.800,1.00,109503.281,9.5,NaN,AVERAGE,109516.523,10.5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN

Dump data with method `to_hdf`.

In [5]:
gfall_reader.to_hdf('gfall.h5')

[               py.warnings][WARNING] - /home/epassaro/miniconda3/envs/carsus/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3343: PerformanceWarning:
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed,key->block1_values] [items->Index(['label_first', 'label_second', 'ref', 'blank3', 'hyperfine_note_first',
       'blank4', 'line_code'],
      dtype='object')]

  exec(code_obj, self.user_global_ns, self.user_ns)
 (warnings.py:99)

[               py.warnings][WARNING] - /home/epassaro/miniconda3/envs/carsus/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3343: PerformanceWarning:
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed,key->block3_values] [items->Index(['ref', 'blank3', 'blank4', 'line_code', 'label_lower', 'label_upper',
       'hyperfine_note_lower', 'hyperfine_note_upper'],
      dtype='object')]

  exec(code_obj, self.user_global_ns, self.user_ns)
 (warnings.py:99)

In [6]:
# Hidden cell
!rm gfall.h5